### ISSUE TITLE
do not know how to change g suites email font to courier

### ISSUE THREAD

**Issue by Hypothalmus** [softprops/courier#20]
need help ....i have no idea how to change font to courier for my emails. I use g suites on andiod google pixel xl phone. If someone could explain to me as if i were a five year old I would be most appreciative.
thank you
shane

**Comment by softprops** [comment]
I think you may have arrived at the wrong place my friend. This is a repository for a Scala library for sending email. This is not a font repository or support channel for mail apps on phones.

**Comment by Hypothalmus** [comment]
sorry

NOTICE:This electronic mail may contain information that is privileged,
confidential or exempt from disclosure under applicable law. Any
dissemination, copying or use of this electronic mail by or to anyone other
than the designated and intended recipient(s) is unauthorized. If you
received this message in error, delete it from your system and contact
sender immediately. E-mail is covered by the Electronic Communications
Privacy Act, 18 U.S.C. §§ 2510-2521 and is legally privileged.
