### ISSUE TITLE
maintenance

### ISSUE THREAD

**Issue by daddykotex** [softprops/courier#36]
Hi, I think this project needs a little maintenance and I would like to know if I can submit PR here and they will be considered or if I should go ahead and fork the repository.

- upgrade javax.mail
- make it opt-in to use a `Future` and allow for other type constructor to be used for asynchronous computation
- scalafmt, sbt 1.0, etc.

I have already started the work on my fork https://github.com/daddykotex/courier

Thanks, David

**Comment by softprops** [comment]
That sound perfect! At one point someone was interested in a repo transfer but never followed up. I would be delighted for someone to step up and own this project. I no longer have time to do that myself. Would you be interested in a transfer of ownership? It's a built in feature of github

**Comment by daddykotex** [comment]
I've never maintained software that is actually used, but yes, I'd be happy to take the lead.

**Comment by daddykotex** [comment]
Whenever you have time 😄

**Comment by ticofab** [comment]
It seems that history repeats itself 😄

**Comment by dmurvihill** [comment]
Hi @softprops,

We use Courier in production, so I would be happy to take over as maintainer if no one else is available to do it. Just need the right level of access here and on Maven central.

**Comment by daddykotex** [comment]
Just to be clear @softprops 

I have had a positive response as you can see from the comment above. But I was never promoted to a maintainer neither here or on maven central.

In the end, I forked made some changes and published a new version: https://search.maven.org/search?q=g:com.github.daddykotex

Note that I've stopped working on the project that required this version of courier, that's what I was trying to tell you in the email.

Also, if you just want to update courier to fix some issues and don't mind switching to a new library (ie:  com.github.daddykotex:courier), we can work together on my fork (publishing setup is done).

**Comment by softprops** [comment]
sry for dropping the ball on this.  I thought I'd handed this repo off before. for now I'll add you both as maintainers. maven central is an odd beast. what I'd recommend is I actually transfer ownership of this repo to one of you to make this easier to manage. that would essentially make your account be the canonical owner. Thoughts @daddykotex @dmurvihill since `com.github.daddykotex` is a new org already published I might suggest @daddykotex grab this one.

**Comment by softprops** [comment]
ok @daddykotex @dmurvihill. I sent out invites for for collaboratorship on this repo. I'm not sure how to change maven central permissions.  I may be best to use the org id @daddykotex created or make a new org id for who ever wants to grab ownership of this repo. Just let me know and I'll be happy do do so.

Again sorry for the long delay. I've haven't been very active in the scala ecosystem for some time.

**Comment by dmurvihill** [comment]
It's all good! Maybe @daddykotex and I can get on the phone for fifteen minutes and decide what we want to do. I'll send details by email.

**Comment by daddykotex** [comment]
@dmurvihill and I will start maintaining this project in the upcoming days/weeks.
