### ISSUE TITLE
Can't get courier via sbt

### ISSUE THREAD

**Issue by vangogh500** [softprops/courier#38]
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: ch.lightshed#courier_2.12;0.1.4: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          ch.lightshed:courier_2.12:0.1.4
...
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) sbt.ResolveException: unresolved dependency: ch.lightshed#cou
rier_2.12;0.1.4: not found

build.sbt:

resolvers += "lightshed-maven" at "http://dl.bintray.com/content/lightshed/maven"
libraryDependencies += "ch.lightshed" %% "courier" % "0.1.4"

**Comment by emanueloliveira23** [comment]
Hi @vangogh500, 

How you resolve this issue?
